apiVersion: v1
kind: Service
metadata:
  name: {{ include "todos.fullname" . }}-api
  labels:
{{ include "todos.labels" . | indent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "todos.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}-api
