apiVersion: v1
kind: Service
metadata:
  name: {{ include "todos.fullname" . }}-front
  labels:
{{ include "todos.labels" . | indent 4 }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "todos.name" . }}-front
    app.kubernetes.io/instance: {{ .Release.Name }}-front
