apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todos.fullname" . }}-front
  labels:
{{ include "todos.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todos.name" . }}-front
      app.kubernetes.io/instance: {{ .Release.Name }}-front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todos.name" . }}-front
        app.kubernetes.io/instance: {{ .Release.Name }}-front
    spec:
    {{- with .Values.front.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-front
          image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}"
          imagePullPolicy: {{ .Values.front.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.front.resources | nindent 12 }}
      {{- with .Values.front.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.front.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.front.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
