apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todos.fullname" . }}-postgres
  labels:
{{ include "todos.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todos.name" . }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todos.name" . }}-postgres
        app.kubernetes.io/instance: {{ .Release.Name }}-postgres
    spec:
    {{- with .Values.postgres.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      {{- with .Values.postgres.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.postgres.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.postgres.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
